import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Stack from "@mui/material/Stack";
import * as O from "fp-ts/Option"
import {Tab, Tabs} from "@mui/material";
import {useEffect, useState} from "react";
import {useRouter} from "next/router";
import {useSelector} from "react-redux";
import {selectAuthState} from "@/redux/auth";
import {isNone} from "fp-ts/Option";
import {UserT} from "@/domain/auth";
import {Box} from "@mui/system";
import {TabPanel} from "@/components/tabPanel";
import CreateGame from "@/components/createGame";
import JoinGame from "@/components/joinGame";

export default function Home() {
  const router = useRouter()
  const authState = useSelector(selectAuthState);
  const user = authState.user

  useEffect(() => {
    if (isNone(authState.user)) router.push("/auth")
  }, [authState.user, router]);

  const [activeTab, setActiveTab] = useState(0);
  const onTabChange = (event: React.SyntheticEvent, newValue: number) => {
    setActiveTab(newValue);
  };

  function renderForUser(knownUser: UserT) {
    return (
      <Stack spacing={2} sx={{ width: "100%", maxWidth: "500px", marginTop: "5rem" }}>
        <Box sx={{ borderBottom: 1, borderColor: 'divider' }}>
          <Tabs value={activeTab} onChange={onTabChange}>
            <Tab label="Join game" />
            <Tab label="Create game" />
          </Tabs>
        </Box>
        <TabPanel value={activeTab} index={0}>
          <JoinGame user={knownUser}></JoinGame>
        </TabPanel>
        <TabPanel value={activeTab} index={1}>
          <CreateGame user={knownUser}></CreateGame>
        </TabPanel>
      </Stack>
    )
  }

  return (
    <>
      <Head>
        <title>Town Racer - Lobby</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {O.match(() => <div></div>, renderForUser)(user)}
      </main>
    </>
  )
}

